import { View, Text, StyleSheet, ScrollView, ActivityIndicator, Image, TouchableOpacity, Modal } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { supabase } from '../../src/lib/supabase';
import { BlurView } from 'expo-blur';

interface ShareData {
  recordingName: string;
  recordingAmount: number;
  recordingType: string;
  date: string;
  perPerson: { name: string; total: number }[];
  items: { name: string; cost: number; subitems: { name: string; cost: number; people: string[] }[] }[];
  payment: { accountName: string; bank: string; accountNumber: string; qrCode: string | null; } | null;
}

export default function SplitSharePage() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const [data, setData] = useState<ShareData | null>(null);
  const [loading, setLoading] = useState(true);
  const [notFound, setNotFound] = useState(false);

  useEffect(() => {
    if (!id) return;
    supabase.from('split_shares').select('data').eq('id', id).single()
      .then(({ data: row, error }) => {
        if (error || !row) setNotFound(true);
        else setData(row.data as ShareData);
        setLoading(false);
      });
  }, [id]);

  if (loading) return <View style={s.center}><ActivityIndicator color="#0ccfcf" /></View>;
  if (notFound || !data) return (
    <View style={s.center}>
      <Text style={{ fontSize: 40 }}>🔍</Text>
      <Text style={s.notFound}>split not found</Text>
    </View>
  );

  const amtColor = data.recordingType === 'expense' ? '#ed6a6a' : data.recordingType === 'income' ? '#2ab671' : '#425252';

  return (
    <>
      <ScrollView style={s.container} contentContainerStyle={s.scroll}>

      {/* Header */}
      <Text style={s.appLabel}>ledgr</Text>
      <Text style={s.recName}>{data.recordingName.toLowerCase()}</Text>
      <Text style={[s.recAmount, { color: amtColor }]}>{Number(data.recordingAmount).toLocaleString('en-US', { minimumFractionDigits: 2 })}</Text>
      <Text style={s.recDate}>{data.date}</Text>

      {/* Per Person Pay */}
      <Text style={s.sectionHeader}>per person pay</Text>
      <View style={s.card}>
        {data.perPerson.map((p, i) => (
          <View key={i}>
            <View style={s.infoRow}>
              <Text style={s.infoLabel}>{p.name}</Text>
              <View style={s.dots} />
              <Text style={s.infoValue}>{p.total.toLocaleString('en-US', { minimumFractionDigits: 2 })}</Text>
            </View>
            {i < data.perPerson.length - 1 && <View style={s.divider} />}
          </View>
        ))}
      </View>

      {/* Item Information */}
      <Text style={s.sectionHeader}>item information</Text>
      {data.items.map((item, ii) => (
        <View key={ii} style={s.itemBlock}>
          <View style={s.itemHeader}>
            <Text style={s.itemName}>{item.name.toLowerCase()}</Text>
            <Text style={s.itemCost}>{item.cost.toLocaleString('en-US', { minimumFractionDigits: 2 })}</Text>
          </View>
          {item.subitems.map((sub, si) => {
            const pp = sub.people.length > 0 ? sub.cost / sub.people.length : sub.cost;
            return (
              <View key={si} style={s.subRow}>
                <Text style={s.arrow}>↳</Text>
                <View style={{ flex: 1, gap: 3 }}>
                  <View style={s.subTop}>
                    <Text style={s.subName}>{sub.name.toLowerCase()}</Text>
                    <Text style={s.subCost}>{sub.cost.toLocaleString('en-US', { minimumFractionDigits: 2 })}</Text>
                  </View>
                  <Text style={s.subSplit}>{sub.people.length} {sub.people.length === 1 ? 'person' : 'people'} · {pp.toLocaleString('en-US', { minimumFractionDigits: 2 })} each</Text>
                  <View style={s.chips}>
                    {sub.people.map((p, pi) => (
                      <View key={pi} style={s.chip}><Text style={s.chipText}>{p}</Text></View>
                    ))}
                  </View>
                </View>
              </View>
            );
          })}
        </View>
      ))}

      {/* Payment Information */}
      {data.payment && (
        <>
          <Text style={s.sectionHeader}>payment information</Text>
          <View style={s.card}>
            <View style={s.payRow}>
              <View style={{ gap: 3, flex: 1 }}>
                <Text style={s.payName}>{data.payment.accountName}</Text>
                <Text style={s.payBank}>{data.payment.bank}</Text>
                <Text style={s.payNumber}>{data.payment.accountNumber}</Text>
              </View>
              {data.payment.qrCode
                ? <TouchableOpacity onPress={() => setQrModal(true)}>
                    <Image source={{ uri: data.payment.qrCode }} style={s.qr} resizeMode="contain" />
                  </TouchableOpacity>
                : null}
            </View>
          </View>
        </>
      )}

      <Text style={s.footer}>generated by ledgr</Text>
    </ScrollView>

    {/* QR Modal */}
    <Modal visible={qrModal} transparent animationType="fade" onRequestClose={() => setQrModal(false)}>
      <BlurView intensity={60} tint="dark" style={s.qrOverlay}>
        <TouchableOpacity style={s.qrOverlay} activeOpacity={1} onPress={() => setQrModal(false)}>
          <Image source={{ uri: data?.payment?.qrCode ?? '' }} style={s.qrLarge} resizeMode="contain" />
          <Text style={s.qrTap}>tap anywhere to close</Text>
        </TouchableOpacity>
      </BlurView>
    </Modal>
    </>
  );
}

const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#ffffff' },
  scroll: { paddingHorizontal: 28, paddingTop: 60, paddingBottom: 60 },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#ffffff', gap: 12 },
  notFound: { fontFamily: 'RobotoMono_400Regular', fontSize: 13, color: '#929090' },
  appLabel: { fontFamily: 'Avenelle', fontSize: 18, color: '#0ccfcf', marginBottom: 8 },
  recName: { fontFamily: 'Avenelle', fontSize: 26, color: '#425252', letterSpacing: -0.5, lineHeight: 30, marginBottom: 4 },
  recAmount: { fontFamily: 'RobotoMono_400Regular', fontSize: 20, marginBottom: 2 },
  recDate: { fontFamily: 'RobotoMono_400Regular', fontSize: 10, color: '#929090', marginBottom: 28 },
  sectionHeader: { fontFamily: 'ChillaxMedium', fontSize: 14, color: '#0ccfcf', letterSpacing: -0.3, marginBottom: 10 },
  card: { backgroundColor: '#fafafa', borderRadius: 14, paddingHorizontal: 16, paddingVertical: 4, borderWidth: 1, borderColor: '#f0f0f0', marginBottom: 24 },
  infoRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10 },
  infoLabel: { fontFamily: 'RobotoMono_400Regular', fontSize: 12, color: '#425252', flexShrink: 0 },
  dots: { flex: 1, borderBottomWidth: 1, borderStyle: 'dotted', borderColor: '#d0d0d0', marginHorizontal: 8 },
  infoValue: { fontFamily: 'RobotoMono_700Bold', fontSize: 12, color: '#425252', flexShrink: 0 },
  divider: { height: 1, backgroundColor: '#f0f0f0' },
  itemBlock: { backgroundColor: '#fafafa', borderRadius: 14, padding: 14, borderWidth: 1, borderColor: '#f0f0f0', marginBottom: 10 },
  itemHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
  itemName: { fontFamily: 'RobotoMono_700Bold', fontSize: 13, color: '#425252' },
  itemCost: { fontFamily: 'RobotoMono_400Regular', fontSize: 12, color: '#929090' },
  subRow: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  arrow: { fontSize: 11, color: '#c0c0c0', marginTop: 2 },
  subTop: { flexDirection: 'row', justifyContent: 'space-between' },
  subName: { fontFamily: 'RobotoMono_700Bold', fontSize: 11, color: '#425252' },
  subCost: { fontFamily: 'RobotoMono_400Regular', fontSize: 11, color: '#929090' },
  subSplit: { fontFamily: 'RobotoMono_400Regular', fontSize: 10, color: '#929090' },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 4 },
  chip: { backgroundColor: '#f0f0f0', borderRadius: 999, paddingVertical: 3, paddingHorizontal: 8 },
  chipText: { fontFamily: 'RobotoMono_400Regular', fontSize: 10, color: '#425252' },
  payRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12 },
  payName: { fontFamily: 'ChillaxMedium', fontSize: 14, color: '#425252' },
  payBank: { fontFamily: 'RobotoMono_400Regular', fontSize: 10, color: '#929090' },
  payNumber: { fontFamily: 'RobotoMono_700Bold', fontSize: 13, color: '#425252' },
  qr: { width: 80, height: 80, borderRadius: 8 },
  qrOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  qrLarge: { width: 260, height: 260, borderRadius: 16 },
  qrTap: { fontFamily: 'RobotoMono_400Regular', fontSize: 11, color: 'rgba(255,255,255,0.5)', marginTop: 16 },
  footer: { fontFamily: 'RobotoMono_400Regular', fontSize: 10, color: '#c0c0c0', textAlign: 'center', marginTop: 24 },
});
