$f='c:\Users\jhoeb\OneDrive\Documents\Work\Apps\Financial Help\ledgr\app\(app)\add-recording.tsx'
$lines=[IO.File]::ReadAllLines($f,[Text.Encoding]::UTF8)
$before=$lines[0..302]   # up to line before handleSave
$after=$lines[514..($lines.Length-1)]  # from openExpensePicker onwards

$newSave=@(
'  const handleSave = async () => {',
'    const invalid = items.find(it => !it.name.trim() || !it.amount);',
'    if (invalid) { setError("name and amount are required for all items."); return; }',
'    setLoading(true); setError("");',
'    try {',
'      const { data: { user } } = await supabase.auth.getUser();',
'      const statusMap: Record<string, string> = {',
'        expense: "paid", income: "received", savings: "saved",',
'        payable: "unpaid", receivable: "pending", expense_receivable: "paid",',
'      };',
'',
'      if (editId) {',
'        // Edit mode: update first item only',
'        const it = items[0];',
'        const { error: err } = await supabase.from("recordings").update({',
'          name: it.name.trim(), type, amount: parseFloat(it.amount),',
'          transaction_date: date, notes: notes.trim() || null,',
'          category_id: it.category?.id || null,',
'          account_id: it.account?.id || null,',
'          currency,',
'        }).eq("id", editId);',
'        if (err) throw err;',
'      } else {',
'        // Multi-item save',
'        for (const it of items) {',
'          const effectiveAccount = useSingularAccount ? singularAccount : it.account;',
'          const effectivePerson  = useSingularPerson  ? singularPerson  : it.person;',
'          const effectivePersonId = useSingularPerson ? singularPersonUserId : it.personUserId;',
'          const effectiveType = type === "expense" && it.isReceivable ? "expense_receivable" : type;',
'          const isComboItem = effectiveType === "expense_receivable";',
'          const isLoanItem  = effectiveType === "receivable" || effectiveType === "payable";',
'',
'          if (isComboItem) {',
'            const { data: expRec, error: expErr } = await supabase.from("recordings").insert({',
'              space_id: spaceId, user_id: user!.id, name: it.name.trim(), type: "expense",',
'              amount: parseFloat(it.amount), transaction_date: date, notes: notes.trim() || null,',
'              category_id: it.category?.id || null, account_id: effectiveAccount?.id || null,',
'              status: "paid", is_due: true,',
'              person_name: effectivePerson || null, tagged_friend_user_id: effectivePersonId || null, currency,',
'            }).select("id").single();',
'            if (expErr) throw expErr;',
'            await supabase.from("recordings").insert({',
'              space_id: spaceId, user_id: user!.id, name: it.name.trim(), type: "receivable",',
'              amount: parseFloat(it.amount), transaction_date: date, notes: notes.trim() || null,',
'              category_id: it.category?.id || null, account_id: effectiveAccount?.id || null,',
'              status: "pending", person_name: effectivePerson || null,',
'              linked_recording_id: expRec!.id, currency,',
'            });',
'          } else {',
'            const { data: newRec, error: err } = await supabase.from("recordings").insert({',
'              space_id: spaceId, user_id: user!.id, name: it.name.trim(), type: effectiveType,',
'              amount: parseFloat(it.amount), transaction_date: date, notes: notes.trim() || null,',
'              category_id: it.category?.id || null,',
'              account_id: effectiveAccount?.id || null,',
'              status: statusMap[effectiveType] ?? "paid",',
'              person_name: (isLoanItem || isComboItem) ? effectivePerson || null : null,',
'              tagged_friend_user_id: (isLoanItem || isComboItem) ? effectivePersonId || null : null,',
'              currency,',
'            }).select("id").single();',
'            if (err) throw err;',
'            // Budget warning',
'            if (effectiveType === "expense" && spaceId && spaceBudget && newRec?.id) {',
'              const newSpent = spaceSpent + parseFloat(it.amount);',
'              const pct = newSpent / spaceBudget;',
'              const monthStart = new Date(); monthStart.setDate(1); monthStart.setHours(0,0,0,0);',
'              if (pct >= 1.0) {',
'                const { data: ex } = await supabase.from("notifications").select("id").eq("user_id", user!.id).eq("type","budget_limit_reached").contains("data",{spaceId}).gte("created_at",monthStart.toISOString()).maybeSingle();',
'                if (!ex) await supabase.from("notifications").insert({ user_id: user!.id, type:"budget_limit_reached", title:"you\'ve hit your budget limit", body:`${spaceName} has exceeded its budget`, message:`${spaceName} has exceeded its budget`, data:{spaceId,spaceName}, is_read:false, status:"new" });',
'              } else if (pct >= 0.8) {',
'                const { data: ex } = await supabase.from("notifications").select("id").eq("user_id", user!.id).eq("type","budget_warning_80").contains("data",{spaceId}).gte("created_at",monthStart.toISOString()).maybeSingle();',
'                if (!ex) await supabase.from("notifications").insert({ user_id: user!.id, type:"budget_warning_80", title:"you\'ve used 80% of your budget", body:`${spaceName} is almost at its limit`, message:`${spaceName} is almost at its limit`, data:{spaceId,spaceName}, is_read:false, status:"new" });',
'              }',
'            }',
'            // Receipt upload',
'            if (newRec?.id && it.photos.length > 0) {',
'              const { data: { user: u } } = await supabase.auth.getUser();',
'              const { data: entry } = await supabase.from("receipt_entries").insert({ user_id: u!.id, note: it.name.trim(), recording_id: newRec.id }).select().single();',
'              if (entry?.id) {',
'                for (const uri of it.photos) {',
'                  const compressed = await compressImage(uri);',
'                  try { await uploadReceiptPhoto(compressed, entry.id); }',
'                  catch (uploadErr: any) { if (uploadErr?.message === "RECEIPT_LIMIT_REACHED") { setError("monthly receipt limit reached."); } break; }',
'                }',
'              }',
'            }',
'          }',
'        }',
'      }',
'      setPendingFocusDate(date);',
'      handleClose();',
'    } catch (e: any) {',
'      setError(e.message);',
'      setLoading(false);',
'    }',
'  };',
''
)

$result=$before+$newSave+$after
[IO.File]::WriteAllLines($f,$result,[Text.Encoding]::UTF8)
Write-Output ('Done lines='+$result.Length)
